### ISSUE TITLE
Hanging on build in the make step

### ISSUE THREAD

**Issue by zjeaton** [joelkoz/xtwsd#6]
Hello,

I have been attempting to build in a fresh install of Ubuntu 20.04 on Windows. I have had to step back and install a lot of dependencies, but I'm now completely stuck here in the make:

```
[ 51%] Building CXX object CMakeFiles/xtwsd.dir/src/jsonxt.cpp.o
```

It is throwing errors and warnings stating it could not convert. There are 6 of them. Example:

```
xtwsd/src/jsonxt.cpp:312:60: error: could not convert ‘find_tzfile’ from ‘int32_t (*)(char*)’ {aka ‘int (*)(char*)’} to ‘std::function<int(const char*)>’
  312 |         rec.header.tzfile = getEnumProperty(j, "timezone", find_tzfile);
```

I have very little experience with C or C++, so I'm banging my head against the wall.  thanks
